require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JuzgadosController do

  # This should return the minimal set of attributes required to create a valid
  # Juzgado. As you add validations to Juzgado, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JuzgadosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all juzgados as @juzgados" do
      juzgado = Juzgado.create! valid_attributes
      get :index, {}, valid_session
      assigns(:juzgados).should eq([juzgado])
    end
  end

  describe "GET show" do
    it "assigns the requested juzgado as @juzgado" do
      juzgado = Juzgado.create! valid_attributes
      get :show, {:id => juzgado.to_param}, valid_session
      assigns(:juzgado).should eq(juzgado)
    end
  end

  describe "GET new" do
    it "assigns a new juzgado as @juzgado" do
      get :new, {}, valid_session
      assigns(:juzgado).should be_a_new(Juzgado)
    end
  end

  describe "GET edit" do
    it "assigns the requested juzgado as @juzgado" do
      juzgado = Juzgado.create! valid_attributes
      get :edit, {:id => juzgado.to_param}, valid_session
      assigns(:juzgado).should eq(juzgado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Juzgado" do
        expect {
          post :create, {:juzgado => valid_attributes}, valid_session
        }.to change(Juzgado, :count).by(1)
      end

      it "assigns a newly created juzgado as @juzgado" do
        post :create, {:juzgado => valid_attributes}, valid_session
        assigns(:juzgado).should be_a(Juzgado)
        assigns(:juzgado).should be_persisted
      end

      it "redirects to the created juzgado" do
        post :create, {:juzgado => valid_attributes}, valid_session
        response.should redirect_to(Juzgado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved juzgado as @juzgado" do
        # Trigger the behavior that occurs when invalid params are submitted
        Juzgado.any_instance.stub(:save).and_return(false)
        post :create, {:juzgado => {}}, valid_session
        assigns(:juzgado).should be_a_new(Juzgado)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Juzgado.any_instance.stub(:save).and_return(false)
        post :create, {:juzgado => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested juzgado" do
        juzgado = Juzgado.create! valid_attributes
        # Assuming there are no other juzgados in the database, this
        # specifies that the Juzgado created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Juzgado.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => juzgado.to_param, :juzgado => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested juzgado as @juzgado" do
        juzgado = Juzgado.create! valid_attributes
        put :update, {:id => juzgado.to_param, :juzgado => valid_attributes}, valid_session
        assigns(:juzgado).should eq(juzgado)
      end

      it "redirects to the juzgado" do
        juzgado = Juzgado.create! valid_attributes
        put :update, {:id => juzgado.to_param, :juzgado => valid_attributes}, valid_session
        response.should redirect_to(juzgado)
      end
    end

    describe "with invalid params" do
      it "assigns the juzgado as @juzgado" do
        juzgado = Juzgado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Juzgado.any_instance.stub(:save).and_return(false)
        put :update, {:id => juzgado.to_param, :juzgado => {}}, valid_session
        assigns(:juzgado).should eq(juzgado)
      end

      it "re-renders the 'edit' template" do
        juzgado = Juzgado.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Juzgado.any_instance.stub(:save).and_return(false)
        put :update, {:id => juzgado.to_param, :juzgado => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested juzgado" do
      juzgado = Juzgado.create! valid_attributes
      expect {
        delete :destroy, {:id => juzgado.to_param}, valid_session
      }.to change(Juzgado, :count).by(-1)
    end

    it "redirects to the juzgados list" do
      juzgado = Juzgado.create! valid_attributes
      delete :destroy, {:id => juzgado.to_param}, valid_session
      response.should redirect_to(juzgados_url)
    end
  end

end
