require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VisitaDiariasController do

  # This should return the minimal set of attributes required to create a valid
  # VisitaDiaria. As you add validations to VisitaDiaria, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VisitaDiariasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all visita_diarias as @visita_diarias" do
      visita_diaria = VisitaDiaria.create! valid_attributes
      get :index, {}, valid_session
      assigns(:visita_diarias).should eq([visita_diaria])
    end
  end

  describe "GET show" do
    it "assigns the requested visita_diaria as @visita_diaria" do
      visita_diaria = VisitaDiaria.create! valid_attributes
      get :show, {:id => visita_diaria.to_param}, valid_session
      assigns(:visita_diaria).should eq(visita_diaria)
    end
  end

  describe "GET new" do
    it "assigns a new visita_diaria as @visita_diaria" do
      get :new, {}, valid_session
      assigns(:visita_diaria).should be_a_new(VisitaDiaria)
    end
  end

  describe "GET edit" do
    it "assigns the requested visita_diaria as @visita_diaria" do
      visita_diaria = VisitaDiaria.create! valid_attributes
      get :edit, {:id => visita_diaria.to_param}, valid_session
      assigns(:visita_diaria).should eq(visita_diaria)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VisitaDiaria" do
        expect {
          post :create, {:visita_diaria => valid_attributes}, valid_session
        }.to change(VisitaDiaria, :count).by(1)
      end

      it "assigns a newly created visita_diaria as @visita_diaria" do
        post :create, {:visita_diaria => valid_attributes}, valid_session
        assigns(:visita_diaria).should be_a(VisitaDiaria)
        assigns(:visita_diaria).should be_persisted
      end

      it "redirects to the created visita_diaria" do
        post :create, {:visita_diaria => valid_attributes}, valid_session
        response.should redirect_to(VisitaDiaria.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved visita_diaria as @visita_diaria" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitaDiaria.any_instance.stub(:save).and_return(false)
        post :create, {:visita_diaria => {}}, valid_session
        assigns(:visita_diaria).should be_a_new(VisitaDiaria)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VisitaDiaria.any_instance.stub(:save).and_return(false)
        post :create, {:visita_diaria => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested visita_diaria" do
        visita_diaria = VisitaDiaria.create! valid_attributes
        # Assuming there are no other visita_diarias in the database, this
        # specifies that the VisitaDiaria created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VisitaDiaria.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => visita_diaria.to_param, :visita_diaria => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested visita_diaria as @visita_diaria" do
        visita_diaria = VisitaDiaria.create! valid_attributes
        put :update, {:id => visita_diaria.to_param, :visita_diaria => valid_attributes}, valid_session
        assigns(:visita_diaria).should eq(visita_diaria)
      end

      it "redirects to the visita_diaria" do
        visita_diaria = VisitaDiaria.create! valid_attributes
        put :update, {:id => visita_diaria.to_param, :visita_diaria => valid_attributes}, valid_session
        response.should redirect_to(visita_diaria)
      end
    end

    describe "with invalid params" do
      it "assigns the visita_diaria as @visita_diaria" do
        visita_diaria = VisitaDiaria.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitaDiaria.any_instance.stub(:save).and_return(false)
        put :update, {:id => visita_diaria.to_param, :visita_diaria => {}}, valid_session
        assigns(:visita_diaria).should eq(visita_diaria)
      end

      it "re-renders the 'edit' template" do
        visita_diaria = VisitaDiaria.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VisitaDiaria.any_instance.stub(:save).and_return(false)
        put :update, {:id => visita_diaria.to_param, :visita_diaria => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested visita_diaria" do
      visita_diaria = VisitaDiaria.create! valid_attributes
      expect {
        delete :destroy, {:id => visita_diaria.to_param}, valid_session
      }.to change(VisitaDiaria, :count).by(-1)
    end

    it "redirects to the visita_diarias list" do
      visita_diaria = VisitaDiaria.create! valid_attributes
      delete :destroy, {:id => visita_diaria.to_param}, valid_session
      response.should redirect_to(visita_diarias_url)
    end
  end

end
